/* eslint-disable react/display-name */
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const TTLogo = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/models/TTLogoSharp.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Sharp.geometry}
        material={materials.Sharp}
        scale={4}
      />
    </group>
  );
});

useGLTF.preload('/models/TTLogoSharp.glb');
