/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function TTLogo(props) {
  const { nodes, materials } = useGLTF('/models/TTLogoSharp.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sharp.geometry}
        material={materials.Sharp}
        scale={4}
      />
    </group>
  );
}

useGLTF.preload('/models/TTLogoSharp.glb');
