import { Hero } from '@/modules/home';

export default function HomePage() {
  return (
    <main className=''>
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
      <Hero />
    </main>
  );
}
