import type { ScheduleItemType } from '@/types';

export const day1: ScheduleItemType[] = [
  {
    title: 'Product Management/Consulting Conference',
    icon: 'FaCalendar',
    id: 'techfiesta-pmconference',
    domain: 'techfiesta',
    color: 'bg-red-700',
    date: 'Oct 4th, 2024',
    location: 'Room 404',
    start: new Date('2024-10-04T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'An insightful conference focusing on the latest trends and challenges in product management and consulting. Attendees will gain valuable knowledge from industry experts.',
    image:
      'https://plus.unsplash.com/premium_photo-1661593062495-08c945c2e077?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Shreya Mirge', phone: '+919876543210' },
      { name: 'Vivaan Kukreja', phone: '+919876543211' },
    ],
    speakers: [
      {
        name: 'Tushar',
        url: 'https://www.linkedin.com/in/tushar-narokar-29988b25a/',
        image: '/imgs/events/speakers/1.png',
        title: 'Media Team Head',
        id: 'tushar',
      },
      {
        name: 'Tushar',
        url: 'https://www.linkedin.com/in/tushar-narokar-29988b25a/',
        image: '/imgs/events/speakers/1.png',
        title: 'Media Team Head',
        id: 'tushar',
      },
    ],
  },
  {
    title: 'How Data is used in Business Intelligence Conference',
    icon: 'FaCalendar',
    id: 'techfiesta-dataconference',
    domain: 'techfiesta',
    color: 'bg-blue-700',
    date: 'Oct 4th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-04T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'A comprehensive session exploring the pivotal role of data in driving business intelligence. Ideal for professionals looking to enhance their data-driven decision-making skills.',
    image:
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543212' },
      { name: 'Pranav Vetkar', phone: '+919876543213' },
    ],
  },
  {
    title: 'Capture the Flag',
    icon: 'FaCalendar',
    id: 'techfiesta-ctf',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: 'Room 406',
    start: new Date('2024-10-04T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'A thrilling cybersecurity challenge where participants test their hacking skills in a controlled environment. A must-attend for those interested in cybersecurity.',
    image:
      'https://images.unsplash.com/photo-1629904869392-ae2a682d4d01?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Anish Patange', phone: '+919876543214' },
      { name: 'Gauri Amale', phone: '+919876543215' },
    ],
    registration: '/#',
  },
  {
    title: 'Fun games (AR/VR, coding games)',
    icon: 'FaCalendar',
    id: 'techfiesta-fungames',
    domain: 'techfiesta',
    color: 'bg-slate-500',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-10-04T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Engage in interactive and innovative games featuring AR/VR technology and coding challenges. Perfect for tech enthusiasts looking to have fun while learning.',
    image:
      'https://images.unsplash.com/photo-1576633587382-13ddf37b1fc1?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Gauri Amale', phone: '+919876543216' },
      { name: 'Swaraj Chavan', phone: '+919876543217' },
    ],
  },
  {
    title: 'Web - 3 Conference',
    icon: 'FaCalendar',
    id: 'techfiesta-web3',
    domain: 'techfiesta',
    color: 'bg-orange-700',
    date: 'Oct 4th, 2024',
    location: 'Room 404',
    start: new Date('2024-10-04T10:30:00'),
    imp: true,
    time: '10:30 AM',
    description:
      'Dive into the future of the internet with this session on Web 3.0, exploring decentralized technologies and their impact on various industries.',
    image:
      'https://images.unsplash.com/photo-1667422380246-3bed910ffae1?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Mihir Palatkar', phone: '+919876543218' },
      { name: 'Sejal Karad', phone: '+919876543219' },
    ],
  },
  {
    title: "LLM's Application in Industry Conference",
    icon: 'FaCalendar',
    id: 'techfiesta-llmconference',
    domain: 'techfiesta',
    color: 'bg-yellow-700',
    date: 'Oct 4th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-04T10:30:00'),
    imp: true,
    time: '10:30 AM',
    description:
      'Explore the practical applications of large language models (LLMs) in different industries. A key session for those interested in AI and machine learning.',
    image:
      'https://images.unsplash.com/photo-1712002641088-9d76f9080889?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Aayush Dhotre', phone: '+919876543220' },
      { name: 'Sakshi Kadam', phone: '+919876543221' },
    ],
  },
  {
    title: 'Drone & Robotics Workshop',
    icon: 'FaCalendar',
    id: 'techfiesta-droneworkshop',
    domain: 'techfiesta',
    color: 'bg-pink-700',
    date: 'Oct 4th, 2024',
    location: 'Room 406',
    start: new Date('2024-10-04T13:00:00'),
    imp: true,
    time: '1:00 PM',
    description:
      'Hands-on workshop on the latest advancements in drone and robotics technology. Participants will learn to build and operate these cutting-edge machines.',
    image:
      'https://plus.unsplash.com/premium_photo-1661727577908-1221ff42dcf8?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Kamlesh Wattamwar', phone: '+919876543222' },
      { name: 'Sanskruti Wattamwar', phone: '+919876543223' },
    ],
  },
  {
    title: 'Gen AI (LLM) Development Workshop',
    icon: 'FaCalendar',
    id: 'techfiesta-genaiworkshop',
    domain: 'techfiesta',
    color: 'bg-purple-700',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-10-04T13:00:00'),
    imp: true,
    time: '1:00 PM',
    description:
      'A deep dive into the development of generative AI and large language models. Essential for developers and AI enthusiasts looking to expand their knowledge.',
    image:
      'https://images.unsplash.com/photo-1675557570482-df9926f61d86?q=80&w=1931&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Atharva Satpute', phone: '+919876543224' },
      { name: 'Sejal Karad', phone: '+919876543225' },
    ],
  },
  {
    title: 'Drone & Robotics Display',
    icon: 'FaCalendar',
    id: 'techfiesta-dronedisplay',
    domain: 'techfiesta',
    color: 'bg-teal-700',
    date: 'Oct 4th, 2024',
    location: 'Open Ground',
    start: new Date('2024-10-04T16:45:00'),
    imp: true,
    time: '4:45 PM',
    description:
      'A live demonstration showcasing the capabilities of modern drones and robotics. Witness the future of automation and aerial technology in action.',
    image:
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    organizers: [
      { name: 'Pritam Rangari', phone: '+919876543226' },
      { name: 'Aayush Musale', phone: '+919876543227' },
    ],
  },
];

export const day2: ScheduleItemType[] = [
  {
    icon: 'FaCalendar',
    title: 'Breakfast and Reporting',
    id: 'esummit-breakfast',
    domain: 'esummit',
    color: 'bg-teal-700',
    date: 'Oct 5th, 2024',
    location: 'Dining Hall',
    start: new Date('2024-10-05T08:00:00'),
    imp: false,
    time: '8:00 AM',
    description:
      "A casual breakfast meeting to kickstart the day, providing an opportunity for networking and discussions on the day's agenda.",
    image: '/imgs/events/schedule/1.jpg',
  },
  {
    icon: 'FaCalendar',
    title: 'Opening Ceremony',
    id: 'mun-opening',
    domain: 'mun',
    color: 'bg-red-500',
    date: 'Oct 5th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-05T09:00:00'),
    imp: false,
    time: '9:00 AM',
    description:
      'The official start of the event, featuring keynote speeches and an overview of the activities planned for the summit.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Chinmay Nakwa', phone: '+919876543246' },
      { name: 'Rutuja Salve', phone: '+919876543247' },
    ],
  },
  {
    title: 'Tier 3 Speaker Sessions x 3',
    icon: 'FaCalendar',
    id: 'esummit-speaker1',
    domain: 'esummit',
    color: 'bg-red-700',
    date: 'Oct 5th, 2024',
    location: 'Room 404',
    start: new Date('2024-10-05T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'A series of insightful talks by industry professionals, covering various topics related to entrepreneurship and innovation.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Sanjana Nagle', phone: '+919876543228' },
      { name: 'Tanvi Sonune', phone: '+919876543229' },
    ],
  },
  {
    title: 'Tier 2 Speaker Session',
    icon: 'FaCalendar',
    id: 'esummit-speaker2',
    domain: 'esummit',
    color: 'bg-purple-700',
    date: 'Oct 5th, 2024',
    location: 'Room 407',
    start: new Date('2024-10-05T11:15:00'),
    imp: true,
    time: '11:15 AM',
    description:
      "A focused session with a prominent speaker discussing advanced topics relevant to the summit's theme.",
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Vaishnav Shinde', phone: '+919876543242' },
      { name: 'Niharika Koul', phone: '+919876543243' },
    ],
  },
  {
    title: 'Tier 3 Speaker Sessions x 2',
    icon: 'FaCalendar',
    id: 'esummit-speaker3',
    domain: 'esummit',
    color: 'bg-blue-700',
    date: 'Oct 5th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-05T12:30:00'),
    imp: true,
    time: '12:30 PM',
    description:
      'Continued discussions from industry experts on crucial topics in business and technology.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Aayush Dhotre', phone: '+919876543230' },
      { name: 'Sakshi Kadam', phone: '+919876543231' },
    ],
  },
  {
    icon: 'FaCalendar',
    title: 'Lunch Break',
    id: 'esummit-lunch',
    color: 'bg-green-700',
    domain: 'esummit',
    date: 'Oct 5th, 2024',
    location: 'Dining Hall',
    start: new Date('2024-10-05T13:30:00'),
    imp: false,
    time: '1:30 PM',
    description:
      'A mid-day break with a catered lunch, allowing attendees to relax and network.',
    image: '/imgs/events/schedule/1.jpg',
  },
  {
    title: 'Tier 2 Speaker Sessions x 2',
    icon: 'FaCalendar',
    id: 'esummit-speaker4',
    domain: 'esummit',
    color: 'bg-yellow-700',
    date: 'Oct 5th, 2024',
    location: 'Room 406',
    start: new Date('2024-10-05T14:15:00'),
    imp: true,
    time: '2:15 PM',
    description:
      'Additional speaker sessions diving into advanced subjects, providing deeper insights into emerging trends.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Kamlesh Wattamwar', phone: '+919876543234' },
      { name: 'Sanskruti Wattamwar', phone: '+919876543235' },
    ],
  },
  {
    title: 'Investors Meeting',
    icon: 'FaCalendar',
    id: 'esummit-investors',
    domain: 'esummit',
    color: 'bg-teal-700',
    date: 'Oct 5th, 2024',
    location: 'Room 407',
    start: new Date('2024-10-05T15:30:00'),
    imp: true,
    time: '3:30 PM',
    description:
      'A key session where startups and entrepreneurs meet potential investors. A vital opportunity for networking and funding discussions.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Atharva Satpute', phone: '+919876543236' },
      { name: 'Sejal Karad', phone: '+919876543237' },
    ],
  },
  {
    icon: 'FaCalendar',
    title: 'Closing Ceremony and Dinner',
    id: 'esummit-closing',
    color: 'bg-orange-700',
    domain: 'esummit',
    date: 'Oct 5th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-05T17:45:00'),
    imp: false,
    time: '5:45 PM',
    description:
      "The final event of the day, celebrating the summit's success with an official closing ceremony and a gala dinner.",
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Gauri Amale', phone: '+919876543238' },
      { name: 'Anish Patange', phone: '+919876543239' },
    ],
  },
];

export const day3: ScheduleItemType[] = [
  // Creator's Conclave
  {
    title: 'PUNE OPEN MIC (Session 1)',
    icon: 'FaCalendar',
    id: 'creatorsconclave-openmic1',
    domain: 'creators',
    color: 'bg-red-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'An open platform for creators and artists to showcase their talent. A diverse range of performances and presentations.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543248' },
      { name: 'Neelam Gupta', phone: '+919876543249' },
    ],
  },
  {
    title: 'Stand UP 1',
    icon: 'FaCalendar',
    id: 'creatorsconclave-standup1',
    domain: 'creators',
    color: 'bg-green-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T12:30:00'),
    imp: true,
    time: '12:30 PM',
    description:
      'A session dedicated to stand-up comedy, featuring local comedians delivering their best routines.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Sanskruti Wattamwar', phone: '+919876543252' },
      { name: 'Swaraj Chavan', phone: '+919876543253' },
    ],
  },
  {
    title: 'Theater Act',
    icon: 'FaCalendar',
    id: 'creatorsconclave-theater',
    domain: 'creators',
    color: 'bg-orange-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T14:00:00'),
    imp: true,
    time: '2:00 PM',
    description:
      'A live theater performance, bringing drama and storytelling to the stage. An engaging cultural experience for all attendees.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Aayush Musale', phone: '+919876543256' },
      { name: 'Rutuja Salve', phone: '+919876543257' },
    ],
  },
  {
    title: 'PUNE OPEN MIC (Session 2)',
    icon: 'FaCalendar',
    id: 'creatorsconclave-openmic2',
    domain: 'creators',
    color: 'bg-red-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T14:30:00'),
    imp: true,
    time: '2:30 PM',
    description:
      'A continuation of the open mic event, offering more creators the chance to perform and share their work.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543248' },
      { name: 'Neelam Gupta', phone: '+919876543249' },
    ],
  },
  {
    title: 'Battle of Comedians',
    icon: 'FaCalendar',
    id: 'creatorsconclave-comedians',
    domain: 'creators',
    color: 'bg-pink-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T15:00:00'),
    imp: true,
    time: '3:00 PM',
    description:
      'A competitive comedy event where comedians battle it out for the top spot, guaranteed to be full of laughs and entertainment.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Vikram Sharma', phone: '+919876543260' },
      { name: 'Sejal Karad', phone: '+919876543261' },
    ],
  },
  {
    title: 'Prize Distribution',
    icon: 'FaCalendar',
    id: 'creatorsconclave-prize',
    domain: 'creators',
    color: 'bg-yellow-500',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T15:45:00'),
    imp: true,
    time: '3:45 PM',
    description:
      'The official prize-giving ceremony, recognizing the best performances and contributions across the event.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Sakshi Kadam', phone: '+919876543261' },
      { name: 'Madiha Shaikh', phone: '+919876543278' },
    ],
  },
  {
    title: 'Main Stage Event',
    icon: 'FaCalendar',
    id: 'creatorsconclave-mainstage',
    domain: 'creators',
    color: 'bg-teal-700',
    date: 'Oct 6th, 2024',
    location: 'Main Stage',
    start: new Date('2024-10-06T17:00:00'),
    imp: true,
    time: '5:00 PM',
    description:
      'A grand finale event on the main stage, bringing together the highlights of the conclave for a spectacular closing.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543278' },
      { name: 'Gauri Amale', phone: '+919876543279' },
    ],
  },

  // E-Sports
  {
    title: 'LAN Tournaments',
    icon: 'FaCalendar',
    id: 'esports-lantournaments',
    domain: 'esports',
    color: 'bg-red-500',
    date: 'Oct 6th, 2024',
    location: 'Gaming Arena',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'Competitive gaming tournaments, featuring popular LAN games. A must-attend for eSports enthusiasts.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Atharva Pednekar', phone: '+919876543266' },
      { name: 'Devika Mule', phone: '+919876543267' },
    ],
  },
  {
    title: 'Competitions',
    icon: 'FaCalendar',
    id: 'esports-competitions',
    color: 'bg-blue-500',
    domain: 'esports',
    date: 'Oct 6th, 2024',
    location: 'Gaming Arena',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'Various gaming competitions where participants can showcase their skills and compete for prizes.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Amit Patel', phone: '+919876543268' },
      { name: 'Snehal Deshmukh', phone: '+919876543269' },
    ],
  },
  {
    title: 'Experience Arenas',
    icon: 'FaCalendar',
    id: 'esports-experience',
    domain: 'esports',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: 'Experience Hall',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'Interactive experience zones offering attendees a chance to try out the latest gaming technology and experiences.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Kamlesh Wattamwar', phone: '+919876543270' },
      { name: 'Aarti Sinha', phone: '+919876543271' },
    ],
  },

  // MUN (Day 2)
  {
    icon: 'FaCalendar',
    title: 'Breakfast and Reporting',
    id: 'mun-breakfast',
    domain: 'mun',
    color: 'bg-slate-400',
    date: 'Oct 6th, 2024',
    location: 'Dining Hall',
    start: new Date('2024-10-06T09:00:00'),
    imp: false,
    time: '9:00 AM',
    description:
      'A morning session to discuss the agenda for the day, accompanied by a light breakfast.',
    image: '/imgs/events/schedule/1.jpg',
  },
  {
    title: 'Committee Session 3',
    icon: 'FaCalendar',
    id: 'mun-committeesession3',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Various Rooms',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'Continuing discussions and debates within various committees, focusing on global and local issues.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Aayush Musale', phone: '+919876543256' },
      { name: 'Rutuja Salve', phone: '+919876543257' },
    ],
  },
  {
    icon: 'FaCalendar',
    title: 'Lunch',
    id: 'mun-lunch',
    domain: 'mun',
    color: 'bg-slate-300',
    date: 'Oct 6th, 2024',
    location: 'Dining Hall',
    start: new Date('2024-10-06T13:00:00'),
    imp: false,
    time: '1:00 PM',
    description:
      'A break for lunch, offering time to recharge before the afternoon sessions.',
    image: '/imgs/events/schedule/1.jpg',
  },
  {
    title: 'Committee Session 4',
    icon: 'FaCalendar',
    id: 'mun-committeesession4',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Various Rooms',
    start: new Date('2024-10-06T14:00:00'),
    imp: true,
    time: '2:00 PM',
    description:
      "The final round of committee sessions, concluding the day's discussions and resolutions.",
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543278' },
      { name: 'Neelam Gupta', phone: '+919876543249' },
    ],
  },
  {
    title: 'High Tea and Closing Ceremony',
    icon: 'FaCalendar',
    id: 'mun-closing',
    domain: 'mun',
    color: 'bg-green-600',
    date: 'Oct 6th, 2024',
    location: 'Lobby Area',
    start: new Date('2024-10-06T16:00:00'),
    imp: false,
    time: '4:00 PM',
    description:
      'A relaxed session with high tea, followed by the official closing ceremony of the MUN event.',
    image: '/imgs/events/schedule/1.jpg',
    organizers: [
      { name: 'Madiha Shaikh', phone: '+919876543278' },
      { name: 'Gauri Amale', phone: '+919876543279' },
    ],
  },
];
