import type { ScheduleItemType } from '@/types';
import { MUNLINK } from '@/config';

export const day1: ScheduleItemType[] = [
  {
    title: 'Tenet Inaugration ceremony',
    icon: 'FaCalendar',
    id: 'tenet-inauguration',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose Hall (MPH)',
    start: new Date('2024-09-12T09:00:00'),
    imp: false,
    time: '8:30 AM',
    description: 'The official opening ceremony for Tenet 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Niranjana Patil' }],
  },
  {
    title: 'Product Management in Tech',
    icon: 'FaCalendar',
    id: 'product-management',
    domain: 'techfiesta',
    color: 'bg-blue-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose hall (MPH)',
    start: new Date('2024-09-12T11:14:00'),
    imp: true,
    time: '2:00 - 3:00',
    description:
      'The Product Management session at TechFiesta will delve into effective product management strategies and best practices tailored for the tech industry. Set in the Multipurpose Hall (MPH) on October 4th, 2024, at 11:15 AM, this session will feature Himanshi Yaduwanshi, Senior Product Manager at Telstra. Himanshi brings a wealth of experience and expertise in balancing business acumen with technical proficiency to successfully deliver products in the competitive tech landscape. This session will cover various facets of product management, such as navigating the product lifecycle, aligning development with customer needs, and creating a cohesive roadmap. With a focus on the dynamic nature of technology, attendees will gain insights into overcoming challenges unique to tech product management and how to build cross-functional teams that drive innovation and growth. This is an ideal opportunity for aspiring and seasoned product managers to learn from a leader in the field and refine their approach to building successful tech products.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/pm.jpg',
    organizers: [
      { name: 'Gargi Bharshankar', phone: '8669033795' },
      { name: 'Shreya Kulkarni', phone: '8669033795' },
    ],
    speakers: ['himanshi-yaduwanshi'],
  },
  {
    title: 'Den Of Code',
    icon: 'FaCalendar',
    id: 'denofcode',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: 'Admin Area, IOIT',
    start: new Date('2024-09-12T11:11:00'),
    imp: true,
    time: '11:00 - 4:00',
    description:
      'Den of Code is an engaging coding event where participants can choose between two thrilling challenges: Webmaster Wars, where they recreate HTML components, or Catch the Bug, where they debug and solve Python code. Participants who successfully complete their chosen challenge will be rewarded with exciting goodies! This event is perfect for those looking to showcase their coding skills and problem-solving abilities in a competitive and fun environment.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/den+of+code.jpeg',
    organizers: [
      { name: 'Atharva Pednekar', phone: '9130912373' },
      { name: 'Swaroop Patil', phone: '9172061027' },
    ],
    speakers: ['himanshi-yaduwanshi'],
  },
  {
    title: 'AI summit panel',
    icon: 'GiArtificialIntelligence',
    id: 'ai-summit-panel',
    domain: 'techfiesta',
    color: 'bg-purple-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose hall (MPH)',
    start: new Date('2024-09-12T11:15:00'),
    imp: true,
    time: '11:15 - 12: 15',
    description:
      'The panel features industry veterans like Uday Kothari, Co-Chair of TiE Pune Angels and Founder of DLT Geeks. With over 30 years of experience in technology and business, Uday brings deep expertise in AI, blockchain, and entrepreneurial mentorship. He will be joined by other distinguished speakers who will discuss AI’s role in business transformation, ethical considerations, and emerging opportunities. Attendees can expect an engaging session that highlights real-world applications of AI, insights into startup ecosystems, and how businesses can leverage AI to stay competitive. This session is perfect for AI enthusiasts, entrepreneurs, and professionals looking to deepen their understanding of AIs capabilities and explore the future possibilities of this transformative technology.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/ai.jpg',
    organizers: [
      { name: 'Manav Nayyar', phone: '8698991836' },
      { name: 'Shreya Kulkarni', phone: '8669033795' },
    ],
    speakers: ['udaykothari', 'atul-mehra-94475b8', 'nishantwelpulwar'],
  },
  {
    title: 'Web - 3 panel',
    icon: 'FaRobot',
    id: 'web3-panel',
    domain: 'techfiesta',
    color: 'bg-yellow-700',
    date: 'Oct 4th, 2024',
    location: 'COE Auditorium',
    start: new Date('2024-09-12T12:30:00'),
    imp: true,
    time: '12:30 - 1:45',
    description:
      'Join us for the Web 3.0 Panel at TechFiesta on October 4th, 2024, at 12:30 PM in the Multipurpose Hall (MPH). This insightful discussion will focus on the transformative technologies of Web 3.0, including decentralized networks, blockchain, digital identities, and NFTs. Featuring industry experts like Almas Sayyed, Founder of PuneDAO, Apoorav Vyas, Co-Founder of ActualOne, and Vishnu Korde, Founder and CEO of DeCloud Labs, the panel will explore current trends and future applications of Web 3.0. Don’t miss this opportunity to gain valuable insights and understand how these innovations are reshaping the digital landscape!',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/web3.jpg',
    organizers: [
      { name: 'Aditya Godse', phone: '7248945402' },
      { name: 'Laukik Patil', phone: '9975875657' },
    ],
    speakers: ['almassayyed', 'apooravvyas', 'vishnukorde'],
  },
  {
    title: "First Steps into Development: A Beginner's Guide",
    icon: 'FaCalendar',
    id: 'beginner-dev-guide',
    domain: 'techfiesta',
    color: 'bg-red-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurposr Hall (MPH)',
    start: new Date('2024-09-12T12:30:00'),
    imp: true,
    time: '12:30 - 1:45',
    description:
      'Join us for "First Steps into Development: A Beginners Guide" at TechFiesta on October 4th, 2024, at 12:30 PM in the Multipurpose Hall (MPH). This session is designed for individuals who are new to software development, providing a foundational understanding of key concepts, tools, and best practices. Led by Vishek Pratap, Co-Founder of TechVP, the session will cover essential topics in programming, web development, and emerging technologies like AI, Cyber Security, and Blockchain. With a passion for education and community engagement, Vishek aims to empower participants to kickstart their journey in the tech world. Don’t miss this opportunity to gain insights from an experienced professional and set the stage for your development career!',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/development.jpeg',
    organizers: [{ name: 'Manav Nayyar', phone: '8698991836' }],
    speakers: ['vishekpratap'],
  },
  {
    title: 'Capture the Flag',
    icon: 'FaCalendar',
    id: 'ctf',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: 'AISSMS IOIT 112, 406',
    start: new Date('2024-09-12T13:45:00'),
    imp: true,
    time: '1:45 PM',
    description:
      'The Capture the Flag (CTF) event is an engaging cybersecurity competition, structured around themes like CTI (Cyber Threat Intelligence), reverse engineering, and cryptography. Designed in a Jeopardy-style format, participants will tackle a series of challenges that increase in difficulty over three levels. The event tests both technical and analytical skills, requiring teams to work together to find and exploit vulnerabilities in various systems to capture virtual flags, each represented in {} format. Over the span of 6 hours, participants will navigate through a wide array of puzzles and challenges, starting with basic security concepts and escalating to advanced topics such as malware analysis and cryptographic breaking. Each level will push the teams further, making this an exciting test of endurance, skill, and strategy. Get ready to dive into the world of ethical hacking and prove your expertise in this adrenaline-fueled competition!',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/ctf.jpg',
    organizers: [
      { name: 'Shreya Kulkarni', phone: '8669033795' },
      { name: 'Aditya Godse', phone: '7248945402' },
    ],
    registration: 'https://www.ioittenet.com/register/ctf',
  },
  {
    title: 'Drone Workshop',
    icon: 'FaCalendar',
    id: 'drone-workshop',
    domain: 'techfiesta',
    color: 'bg-blue-700',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-09-12T13:45:00'),
    imp: true,
    time: '1:45 PM',
    description:
      'Master the essentials of drone technology at our hands-on drone workshop. Get crucial training in drone assembly and understand the components used. Exercise drone programming and get a chance to practice flight training.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/drone.jpg',
    organizers: [
      { name: 'Shreya Kulkarni', phone: '8669033795' },
      { name: 'Aditya Sarade', phone: '8451025156' },
    ],
    registration: 'https://www.ioittenet.com/register/drone-workshop',
  },
  {
    title: 'Exploring the Depths of AR/VR',
    icon: 'FaCalendar',
    id: 'arvr-session',
    domain: 'techfiesta',
    color: 'bg-yellow-700',
    date: 'Oct 4th, 2024',
    location: 'COE Auditorium',
    start: new Date('2024-09-12T14:00:00'),
    imp: true,
    time: '2:00 - 3:00',
    description:
      'Exploration of Augmented and Virtual Reality technologies and applications.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/arvr.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    speakers: ['akhtar-faizan'],
  },
  {
    title: 'Machine Learning unleashed',
    icon: 'FaCalendar',
    id: 'mlunleashed',
    domain: 'techfiesta',
    color: 'bg-red-700',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-09-12T15:30:00'),
    imp: true,
    time: '3:30 - 4:45',
    description:
      'Machine Learning Unleashed" is excited to present a speaker session featuring Saurabh Shahane, Founder and CEO of The Machine Learning Company. With extensive expertise in data and AI, Saurabh leads a team focused on groundbreaking research in generative AI, NLP, and computer vision. He has also established TMLC Academy, offering specialized AI programs, and The Data Hire, a job portal connecting top AI talent with companies. Join us to hear Saurabh share his insights on harnessing AI for innovation, business optimization, and sustainable growth.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/machine+learning.jpeg',
    organizers: [
      { name: 'Shreya Kulkarni', phone: '8669033795' },
      { name: 'Gargi Bharshankar', phone: '9356026528' },
    ],
    speakers: ['saurabh-shahane'],
  },
];

export const day2: ScheduleItemType[] = [
  // E-Sports
  {
    icon: 'FaCalendar',
    title: 'BGMI LAN Event',
    id: 'bgmi-lan-event',
    domain: 'esports',
    color: 'bg-red-500',
    date: 'Oct 6th, 2024',
    location: 'MPH',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Join the exciting BGMI LAN tournament as top teams battle it out in a competitive setting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/bgmi.avif',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration:
      'https://docs.google.com/forms/d/e/1FAIpQLScsw5pMP3SjBaMcMrs1i1D96Cu7WttNDxu9vBYcPTS9Yr5oag/closedform',
  },
  {
    title: 'FIFA (FC 24) PS5 Console Event',
    icon: 'FaCalendar',
    id: 'fifa-console-event',
    domain: 'esports',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: 'Room 105',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Experience the thrill of FIFA FC 24 on the PS5. Compete with other players for the top spot!',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/fifa.webp',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration: 'https://forms.gle/dqRBt7KwQF284b2z7',
  },
  {
    title: 'Valorant',
    icon: 'FaCalendar',
    id: 'valorant-online',
    domain: 'esports',
    color: 'bg-purple-500',
    date: 'Oct 6th, 2024',
    location: 'Online',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Gear up for a competitive Valorant showdown as players from across the globe participate in this online tournament.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/valo.webp',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration:
      'https://docs.google.com/forms/d/e/1FAIpQLSdr4PZfpLjOrNdW5JFIcW09oYEjoDIPhvumvIWhOX78MeIaZQ/viewform',
  },

  // MUN

  {
    title: 'MUN Breakfast and Reporting',
    icon: 'FcGlobe',
    id: 'breakfast-reporting-day1',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 5th, 2024',
    location: 'Admin Office',
    start: new Date('2024-10-05T08:00:00'),
    imp: false,
    time: '8:00 AM - 9:00 AM',
    description: 'Start your day with breakfast and reporting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/breakfast.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'IOIT MUN Opening Ceremony',
    icon: 'FcGlobe',
    id: 'opening-ceremony',
    domain: 'mun',
    color: 'bg-red-500',
    date: 'Oct 5th, 2024',
    location: 'MPH',
    start: new Date('2024-10-05T09:00:00'),
    imp: false,
    time: '9:00 AM - 11:00 AM',
    description: 'The official opening ceremony of IOIT MUN 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN Lunch',
    icon: 'FcGlobe',
    id: 'lunch-day1',
    domain: 'mun',
    color: 'bg-green-500',
    date: 'Oct 5th, 2024',
    location: '3rd Floor Terrace',
    start: new Date('2024-10-05T14:00:00'),
    imp: false,
    time: '2:00 PM - 3:00 PM',
    description: 'Lunch break for all IOIT MUN 2024 participants.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/munlunch.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN High tea',
    icon: 'FcGlobe',
    id: 'high-tea-day1',
    domain: 'mun',
    color: 'bg-orange-500',
    date: 'Oct 5th, 2024',
    location: 'In hand',
    start: new Date('2024-10-05T17:00:00'),
    imp: false,
    time: '5:00 PM - 5:30 PM',
    description: 'High tea session for all IOIT MUN 2024 attendees.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/hightea.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },

  {
    title: 'UNSC Committee Session',
    icon: 'FcGlobe',
    id: 'unsc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-blue-500',
    date: 'Oct 5th, 2024',
    location: 'Room 25',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'The UNSC addresses global peace and security issues, focusing on conflict resolution, sanctions, and peacekeeping efforts to maintain international stability. Agenda: Assessing global export controls and technology transfer under the Wassenaar Arrangement.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNSC.png',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
    munpage: 'https://www.ioitmun.com/unsc',
  },
  {
    title: 'UNHRC Committee Session',
    icon: 'FcGlobe',
    id: 'unhrc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-red-500',
    date: 'Oct 5th, 2024',
    location: 'Room 305',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'The UNHRC promotes and protects human rights globally through dialogue and cooperation. Agenda: Discussing the role of state and non-state actors in the Venezuelan crisis, with emphasis on the humanitarian emergency following the presidential elections.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNHRC.png',
    organizers: [{ name: 'Chinmay Nakwa' }, { name: 'Shriya Naphade' }],
    munpage: 'https://www.ioitmun.com/unhrc',
  },
  {
    title: 'AIPPM Committee Session',
    icon: 'FcGlobe',
    id: 'aippm-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-yellow-500',
    date: 'Oct 5th, 2024',
    location: 'Room 206',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'AIPPM brings together diverse political factions to discuss national policies and reforms. Agenda: Deliberating on the introduction of the Aparajita Bill and the demand for a Central Protection Act.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/AIPPM.png',
    organizers: [{ name: 'Tanisha Londhe' }, { name: 'Atharva Pednekar' }],
    munpage: 'https://www.ioitmun.com/aippm',
  },
  {
    title: 'UNCSW Committee Session',
    icon: 'FcGlobe',
    id: 'uncsw-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-pink-500',
    date: 'Oct 5th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      "UNCSW is dedicated to promoting gender equality and women's empowerment globally. Agenda: Implications of human rights violations on women, with emphasis on religion-driven nations.",
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNCSW.png',
    organizers: [{ name: 'Sajal Gulati' }, { name: 'Devang Gandhi' }],
    munpage: 'https://www.ioitmun.com/uncsw',
  },
  {
    title: 'UNODC Committee Session',
    icon: 'FcGlobe',
    id: 'unodc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-gray-500',
    date: 'Oct 5th, 2024',
    location: 'Room 409',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'UNODC combats global drug trafficking and organized crime while promoting justice and integrity. Agenda: Addressing the challenges of money and drug laundering in Special Economic Zones, with special emphasis on the Golden Triangle SEZ.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNODC.png',
    organizers: [{ name: 'Aditya Sarade' }, { name: 'Tanisha Londhe' }],
    munpage: 'https://www.ioitmun.com/unodc',
  },
];

export const day3: ScheduleItemType[] = [
  // Esummit
  {
    title: 'HR Summit',
    id: 'hr-summit',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T11:15:00'),
    imp: true,
    time: '11:15 AM - 12:15 PM',
    domain: 'esummit',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/hrsummit.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'HR Summit" brings together industry leaders to explore the latest trends and innovations in Human Resources. This session will cover topics such as future HR strategies, talent management, and organizational development, providing attendees with valuable insights into building a dynamic and resilient workforce. Speakers like Akash Sangole and Neha Mathur will share their expertise on navigating the evolving HR landscape. Join us at AISSMS COE on Oct 6th, 2024, from 11:15 AM to 12:15 PM to discover new approaches to managing human capital and driving business success.',
    speakers: ['akash-sangole', 'mathurneha'],
  },
  {
    title: 'D2C Summit',
    id: 'd2c-summit',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS MBA College',
    start: new Date('2024-10-06T13:15:00'),
    imp: true,
    domain: 'esummit',
    time: '1:15 PM - 2:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/d2d.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'D2C Summit" is a unique opportunity to learn from pioneers in the direct-to-consumer space and understand what it takes to build a successful brand in today’s competitive market. Featuring prominent speakers like Jaywant Patil, Dadasaheb Bhagat, and Sangeeta Sharma, this session will delve into the nuances of brand building, customer engagement, and scaling D2C businesses. Dont miss this chance to gain valuable insights at AISSMS MBA College on Oct 6th, 2024, from 1:15 PM to 2:15 PM and take your D2C venture to new heights.',
    speakers: ['jaywant-patil', 'dadasahebbhagat', 'sangeeta-sharma-96b882264'],
  },
  {
    title: 'Venture Summit',
    id: 'venture-summit',
    color: 'bg-yellow-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS MBA College',
    start: new Date('2024-10-06T14:15:00'),
    imp: true,
    domain: 'esummit',
    time: '2:15 PM - 3:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/vc.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Venture Summit" offers a deep dive into the world of venture capital, startup ecosystems, and investment opportunities. With distinguished speakers like Rohit Goyal, Uday Kothari, Rajeev Manjrekar, and Yogesh Thite, this session is a must-attend for aspiring entrepreneurs seeking to navigate the complexities of fundraising and startup growth. Join us at AISSMS MBA College on Oct 6th, 2024, from 2:15 PM to 3:15 PM to gain firsthand knowledge from industry experts and learn how to secure funding and scale your business successfully.',
    speakers: [
      'rohit-goyal',
      'udaykothari-esummit',
      'rajeevmanjrekar',
      'startupconsultantyogeshthite',
    ],
  },
  {
    title: 'Starting up in College',
    id: 'starting-up-in-college',
    color: 'bg-orange-500',
    date: 'Oct 6th, 2024',
    location: 'IOIT MPH',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    domain: 'esummit',
    time: '10:00 AM - 11:15 AM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/startupincollege.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Starting Up in College" is an exciting session designed to inspire and empower college students to explore entrepreneurship from a young age. Led by dynamic speakers like Saurabh Mangrulkar, Co-Founder and CEO of EventBeep, this session will delve into the journey of building startups while still pursuing academics. Attendees will gain insights into leveraging college resources, building networks, and converting their ideas into thriving ventures. Join us at IOIT MPH on Oct 6th, 2024, from 10:00 AM to 11:15 AM to discover how to kickstart your entrepreneurial journey right from college!',
    speakers: ['saurabh-mangrulkar'],
  },
  {
    title: 'Governments and startups',
    id: 'governments-and-startups',
    color: 'bg-purple-500',
    date: 'Oct 6th, 2024',
    location: 'IOIT MPH',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    domain: 'esummit',
    time: '10:00 AM - 11:15 AM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/startupinclg.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Governments and Startups" explores the crucial relationship between government bodies and the startup ecosystem. This session will highlight how governments can play a pivotal role in nurturing startups through policies, grants, and regulatory support. Esteemed speakers will discuss real-world examples and strategies to bridge the gap between innovation and policy, helping startups thrive in a structured environment. Be part of this insightful discussion at IOIT MPH on Oct 6th, 2024, from 10:00 AM to 11:15 AM, and understand how to navigate government frameworks to fuel startup growth and success.',
    speakers: ['shyamkerkar'],
  },
  {
    title: 'Advisory and Legal',
    id: 'advisory-and-legal',
    color: 'bg-gray-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T13:15:00'),
    imp: true,
    domain: 'esummit',
    time: '1:15 PM - 2:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/advisoryandlegal.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    speakers: ['sumit-jha', 'chetanbulsari'],
    description:
      'Advisory and Legal" is a crucial session tailored to help startups and businesses understand the importance of legal frameworks and advisory support. Featuring industry experts like Sumit Jha and Chetan Bulsari, the session will guide entrepreneurs on navigating complex legal landscapes, managing compliance, and seeking the right counsel to mitigate risks and drive sustainable growth. Join us at AISSMS COE on Oct 6th, 2024, from 1:15 PM to 2:15 PM to gain invaluable insights that could help you make informed decisions and protect your business interests.',
  },
  {
    title: 'Incubation and Grants',
    id: 'incubation-and-grants',
    color: 'bg-indigo-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T14:15:00'),
    imp: true,
    domain: 'esummit',
    time: '2:15 PM - 3:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/incubation.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Incubation and Grants" offers an opportunity for budding entrepreneurs to delve into the various avenues of securing incubation support and grant funding. This session will cover the fundamentals of applying for incubator programs and grants, equipping participants with the knowledge to access critical resources that can accelerate their startup’s journey from ideation to execution. Attend this session at AISSMS COE on Oct 6th, 2024, from 2:15 PM to 3:15 PM to learn how to leverage these opportunities to scale your venture and achieve success.',
  },

  // MUN (Day 2)

  {
    title: 'MUN Breakfast and Reporting',
    icon: 'FcGlobe',
    id: 'breakfast-reporting-day2',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Admin Office, 3rd Floor',
    start: new Date('2024-10-06T09:00:00'),
    imp: false,
    time: '9:00 AM - 10:00 AM',
    description: 'Start your day with breakfast and reporting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/breakfast.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN Lunch',
    icon: 'FcGlobe',
    id: 'lunch-day2',
    domain: 'mun',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: '3rd Floor Terrace',
    start: new Date('2024-10-06T13:00:00'),
    imp: false,
    time: '1:00 PM - 2:00 PM',
    description: 'Lunch break for all IOIT MUN 2024 participants.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/munlunch.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN High tea and Closing Ceremony',
    icon: 'FcGlobe',
    id: 'high-tea-closing-ceremony',
    domain: 'mun',
    color: 'bg-orange-500',
    date: 'Oct 6th, 2024',
    location: 'MPH',
    start: new Date('2024-10-06T16:00:00'),
    imp: false,
    time: '4:00 PM - 5:00 PM',
    description: 'High tea and closing ceremony to conclude IOIT MUN 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },

  {
    title: 'UNSC Committee Session',
    icon: 'FcGlobe',
    id: 'unsc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unsc',
    registration: MUNLINK,
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Room 002',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'The UNSC addresses global peace and security issues, focusing on conflict resolution, sanctions, and peacekeeping efforts to maintain international stability. Agenda: Assessing global export controls and technology transfer under the Wassenaar Arrangement.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNSC.png',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'UNHRC Committee Session',
    icon: 'FcGlobe',
    id: 'unhrc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unhrc',
    registration: MUNLINK,
    color: 'bg-red-500',
    date: 'Oct 6th, 2024',
    location: 'Room 305',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'The UNHRC promotes and protects human rights globally through dialogue and cooperation. Agenda: Discussing the role of state and non-state actors in the Venezuelan crisis, with emphasis on the humanitarian emergency following the presidential elections.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNHRC.png',
    organizers: [{ name: 'Chinmay Nakwa' }, { name: 'Shriya Naphade' }],
  },
  {
    title: 'AIPPM Committee Session',
    icon: 'FcGlobe',
    id: 'aippm-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/aippm',
    registration: MUNLINK,
    color: 'bg-yellow-500',
    date: 'Oct 6th, 2024',
    location: 'Room 206',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'AIPPM brings together diverse political factions to discuss national policies and reforms. Agenda: Deliberating on the introduction of the Aparajita Bill and the demand for a Central Protection Act.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/AIPPM.png',
    organizers: [{ name: 'Tanisha Londhe' }, { name: 'Atharva Pednekar' }],
  },
  {
    title: 'UNCSW Committee Session',
    icon: 'FcGlobe',
    id: 'uncsw-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/uncsw',
    registration: MUNLINK,
    color: 'bg-pink-500',
    date: 'Oct 6th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'UNCSW is dedicated to promoting gender equality and women’s empowerment globally. Agenda: Implications of human rights violations on women, with emphasis on religion-driven nations.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNCSW.png',
    organizers: [{ name: 'Sajal Gulati' }, { name: 'Devang Gandhi' }],
  },
  {
    title: 'UNODC Committee Session',
    icon: 'FcGlobe',
    id: 'unodc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unodc',
    registration: MUNLINK,
    color: 'bg-gray-500',
    date: 'Oct 6th, 2024',
    location: 'Room 409',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'UNODC combats global drug trafficking and organized crime while promoting justice and integrity. Agenda: Addressing the challenges of money and drug laundering in Special Economic Zones, with special emphasis on the Golden Triangle SEZ.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/UNODC.png',
    organizers: [{ name: 'Aditya Sarade' }, { name: 'Tanisha Londhe' }],
  },
];
