import type { ScheduleItemType } from '@/types';
import { MUNLINK } from '@/config';

export const day1: ScheduleItemType[] = [
  {
    title: 'Tenet Inaugration ceremony',
    icon: 'FaCalendar',
    id: 'tenet-inauguration',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose Hall (MPH)',
    start: new Date('2024-09-12T09:00:00'),
    imp: false,
    time: '8:30 AM',
    description: 'The official opening ceremony for Tenet 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Niranjana Patil' }],
  },
  {
    title: 'Product Management',
    icon: 'FaCalendar',
    id: 'product-management',
    domain: 'techfiesta',
    color: 'bg-blue-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose hall (MPH)',
    start: new Date('2024-09-12T11:15:00'),
    imp: true,
    time: '11:15 AM',
    description:
      'A session focused on product management strategies and best practices.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/pm.jpg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['himanshi-yaduwanshi'],
  },
  {
    title: 'AI summit panel',
    icon: 'GiArtificialIntelligence',
    id: 'ai-summit-panel',
    domain: 'techfiesta',
    color: 'bg-purple-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose hall (MPH)',
    start: new Date('2024-09-12T11:15:00'),
    imp: true,
    time: '11:15 AM',
    description:
      'A panel discussion on the latest trends and developments in AI.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/ai.jpg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['udaykothari', 'atul-mehra-94475b8', 'nishantwelpulwar'],
  },
  {
    title: 'Web - 3 panel',
    icon: 'FaRobot',
    id: 'web3-panel',
    domain: 'techfiesta',
    color: 'bg-yellow-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurpose Hall (MPH)',
    start: new Date('2024-09-12T12:30:00'),
    imp: true,
    time: '12:30 PM',
    description:
      'A discussion on Web 3.0 technologies and their impact on the future of the internet.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/web3.jpg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['almassayyed', 'apooravvyas', 'vishnukorde'],
  },
  {
    title: "First Steps into Development: A Beginner's Guide",
    icon: 'FaCalendar',
    id: 'beginner-dev-guide',
    domain: 'techfiesta',
    color: 'bg-red-700',
    date: 'Oct 4th, 2024',
    location: 'Multipurposr Hall (MPH)',
    start: new Date('2024-09-12T12:30:00'),
    imp: true,
    time: '12:30 PM',
    description:
      'An introductory session for those new to software development.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/development.jpeg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['vishekpratap'],
  },
  {
    title: 'Capture the Flag',
    icon: 'FaCalendar',
    id: 'ctf',
    domain: 'techfiesta',
    color: 'bg-green-700',
    date: 'Oct 4th, 2024',
    location: '112, 4th floor lab',
    start: new Date('2024-09-12T13:45:00'),
    imp: true,
    time: '1:45 PM',
    description:
      'A cybersecurity challenge where participants compete to find and exploit vulnerabilities.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/ctf.jpg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    registration: 'https://www.ioittenet.com/register/ctf',
  },
  {
    title: 'Drone Workshop',
    icon: 'FaCalendar',
    id: 'drone-workshop',
    domain: 'techfiesta',
    color: 'bg-blue-700',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-09-12T13:45:00'),
    imp: true,
    time: '1:45 PM',
    description:
      'Master the essentials of drone technology at our hands-on drone workshop. Get crucial training in drone assembly and understand the components used. Exercise drone programming and get a chance to practice flight training.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/drone.jpg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    registration: 'https://www.ioittenet.com/register/drone-workshop',
  },
  {
    title: 'Exploring the Depths of AR/VR',
    icon: 'FaCalendar',
    id: 'arvr-session',
    domain: 'techfiesta',
    color: 'bg-yellow-700',
    date: 'Oct 4th, 2024',
    location: 'Room 016',
    start: new Date('2024-09-12T14:00:00'),
    imp: true,
    time: '2:00 PM',
    description:
      'Exploration of Augmented and Virtual Reality technologies and applications.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/arvr.jpeg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['akhtar-faizan'],
  },
  {
    title: 'Machine Learning unleashed',
    icon: 'FaCalendar',
    id: 'mlunleashed',
    domain: 'techfiesta',
    color: 'bg-red-700',
    date: 'Oct 4th, 2024',
    location: 'Room 407',
    start: new Date('2024-09-12T15:30:00'),
    imp: true,
    time: '3:30 PM',
    description:
      'Machine Learning Unleashed" is excited to present a speaker session featuring Saurabh Shahane, Founder and CEO of The Machine Learning Company. With extensive expertise in data and AI, Saurabh leads a team focused on groundbreaking research in generative AI, NLP, and computer vision. He has also established TMLC Academy, offering specialized AI programs, and The Data Hire, a job portal connecting top AI talent with companies. Join us to hear Saurabh share his insights on harnessing AI for innovation, business optimization, and sustainable growth.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/development.jpeg',
    organizers: [{ name: 'Shreya Kulkarni' }],
    speakers: ['saurabh-shahane'],
  },
];

export const day2: ScheduleItemType[] = [
  // E-Sports
  {
    icon: 'FaCalendar',
    title: 'BGMI LAN Event',
    id: 'bgmi-lan-event',
    domain: 'esports',
    color: 'bg-red-500',
    date: 'Oct 6th, 2024',
    location: 'MPH',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Join the exciting BGMI LAN tournament as top teams battle it out in a competitive setting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/bgmi.avif',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration:
      'https://docs.google.com/forms/d/e/1FAIpQLScsw5pMP3SjBaMcMrs1i1D96Cu7WttNDxu9vBYcPTS9Yr5oag/closedform',
  },
  {
    title: 'FIFA (FC 24) PS5 Console Event',
    icon: 'FaCalendar',
    id: 'fifa-console-event',
    domain: 'esports',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: 'Room 105',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Experience the thrill of FIFA FC 24 on the PS5. Compete with other players for the top spot!',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/fifa.webp',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration: 'https://forms.gle/dqRBt7KwQF284b2z7',
  },
  {
    title: 'Valorant',
    icon: 'FaCalendar',
    id: 'valorant-online',
    domain: 'esports',
    color: 'bg-purple-500',
    date: 'Oct 6th, 2024',
    location: 'Online',
    start: new Date('2024-10-05T09:00:00'),
    imp: true,
    time: '9:00 AM',
    description:
      'Gear up for a competitive Valorant showdown as players from across the globe participate in this online tournament.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/esports/esports/valo.webp',
    organizers: [{ name: 'Ayush Sangole' }, { name: 'Avdhoot Chavan' }],
    registration:
      'https://docs.google.com/forms/d/e/1FAIpQLSdr4PZfpLjOrNdW5JFIcW09oYEjoDIPhvumvIWhOX78MeIaZQ/viewform',
  },

  // MUN

  {
    title: 'MUN Breakfast and Reporting',
    icon: 'FcGlobe',
    id: 'breakfast-reporting-day1',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 5th, 2024',
    location: 'Admin Office',
    start: new Date('2024-10-05T08:00:00'),
    imp: false,
    time: '8:00 AM - 9:00 AM',
    description: 'Start your day with breakfast and reporting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/breakfast.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'IOIT MUN Opening Ceremony',
    icon: 'FcGlobe',
    id: 'opening-ceremony',
    domain: 'mun',
    color: 'bg-red-500',
    date: 'Oct 5th, 2024',
    location: 'MPH',
    start: new Date('2024-10-05T09:00:00'),
    imp: false,
    time: '9:00 AM - 11:00 AM',
    description: 'The official opening ceremony of IOIT MUN 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN Lunch',
    icon: 'FcGlobe',
    id: 'lunch-day1',
    domain: 'mun',
    color: 'bg-green-500',
    date: 'Oct 5th, 2024',
    location: '3rd Floor Terrace',
    start: new Date('2024-10-05T14:00:00'),
    imp: false,
    time: '2:00 PM - 3:00 PM',
    description: 'Lunch break for all IOIT MUN 2024 participants.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/munlunch.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN High tea',
    icon: 'FcGlobe',
    id: 'high-tea-day1',
    domain: 'mun',
    color: 'bg-orange-500',
    date: 'Oct 5th, 2024',
    location: 'In hand',
    start: new Date('2024-10-05T17:00:00'),
    imp: false,
    time: '5:00 PM - 5:30 PM',
    description: 'High tea session for all IOIT MUN 2024 attendees.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/hightea.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },

  {
    title: 'UNSC Committee Session',
    icon: 'FcGlobe',
    id: 'unsc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-blue-500',
    date: 'Oct 5th, 2024',
    location: 'Room 25',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'The UNSC addresses global peace and security issues, focusing on conflict resolution, sanctions, and peacekeeping efforts to maintain international stability. Agenda: Assessing global export controls and technology transfer under the Wassenaar Arrangement.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unsc.webp',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
    munpage: 'https://www.ioitmun.com/unsc',
  },
  {
    title: 'UNHRC Committee Session',
    icon: 'FcGlobe',
    id: 'unhrc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-red-500',
    date: 'Oct 5th, 2024',
    location: 'Room 305',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'The UNHRC promotes and protects human rights globally through dialogue and cooperation. Agenda: Discussing the role of state and non-state actors in the Venezuelan crisis, with emphasis on the humanitarian emergency following the presidential elections.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unhcr.webp',
    organizers: [{ name: 'Chinmay Nakwa' }, { name: 'Shriya Naphade' }],
    munpage: 'https://www.ioitmun.com/unhrc',
  },
  {
    title: 'AIPPM Committee Session',
    icon: 'FcGlobe',
    id: 'aippm-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-yellow-500',
    date: 'Oct 5th, 2024',
    location: 'Room 206',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'AIPPM brings together diverse political factions to discuss national policies and reforms. Agenda: Deliberating on the introduction of the Aparajita Bill and the demand for a Central Protection Act.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/aippm.jpg',
    organizers: [{ name: 'Tanisha Londhe' }, { name: 'Atharva Pednekar' }],
    munpage: 'https://www.ioitmun.com/aippm',
  },
  {
    title: 'UNCSW Committee Session',
    icon: 'FcGlobe',
    id: 'uncsw-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-pink-500',
    date: 'Oct 5th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      "UNCSW is dedicated to promoting gender equality and women's empowerment globally. Agenda: Implications of human rights violations on women, with emphasis on religion-driven nations.",
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/uncsw.webp',
    organizers: [{ name: 'Sajal Gulati' }, { name: 'Devang Gandhi' }],
    munpage: 'https://www.ioitmun.com/uncsw',
  },
  {
    title: 'UNODC Committee Session',
    icon: 'FcGlobe',
    id: 'unodc-session',
    domain: 'mun',
    registration: MUNLINK,
    color: 'bg-gray-500',
    date: 'Oct 5th, 2024',
    location: 'Room 409',
    start: new Date('2024-10-05T11:00:00'),
    imp: true,
    time: '11:00 AM',
    description:
      'UNODC combats global drug trafficking and organized crime while promoting justice and integrity. Agenda: Addressing the challenges of money and drug laundering in Special Economic Zones, with special emphasis on the Golden Triangle SEZ.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unodc.jpg',
    organizers: [{ name: 'Aditya Sarade' }, { name: 'Tanisha Londhe' }],
    munpage: 'https://www.ioitmun.com/unodc',
  },
];

export const day3: ScheduleItemType[] = [
  // Esummit
  {
    title: 'HR Summit',
    id: 'hr-summit',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T11:15:00'),
    imp: true,
    time: '11:15 AM - 12:15 PM',
    domain: 'esummit',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/hrsummit.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Explore the latest trends in Human Resources with industry leaders. Discover the future of HR strategies, talent management, and organizational development.',
    speakers: ['akash-sangole', 'mathurneha'],
  },
  {
    title: 'D2C Summit',
    id: 'd2c-summit',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS MBA College',
    start: new Date('2024-10-06T13:15:00'),
    imp: true,
    domain: 'esummit',
    time: '1:15 PM - 2:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/d2d.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Get insights from D2C pioneers and learn what it takes to build a successful direct-to-consumer brand in today’s competitive market.',
    speakers: ['jaywant-patil', 'dadasahebbhagat', 'sangeeta-sharma-96b882264'],
  },
  {
    title: 'Venture Summit',
    id: 'venture-summit',
    color: 'bg-yellow-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS MBA College',
    start: new Date('2024-10-06T14:15:00'),
    imp: true,
    domain: 'esummit',
    time: '2:15 PM - 3:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/vc.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Explore venture capital, startup ecosystems, and investment opportunities with top industry experts. A must-attend for aspiring entrepreneurs.',
    speakers: [
      'rohit-goyal',
      'udaykothari-esummit',
      'rajeevmanjrekar',
      'startupconsultantyogeshthite',
    ],
  },
  {
    title: 'Governments and startups',
    id: 'starting-up-in-college',
    color: 'bg-purple-500',
    date: 'Oct 6th, 2024',
    location: 'IOIT MPH',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    domain: 'esummit',
    time: '10:00 AM - 11:15 AM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/startupinclg.jpeg ',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description: 'An exciting session for college students',
    speakers: ['shyamkerkar'],
  },
  {
    title: 'Advisory and Legal',
    id: 'advisory-and-legal',
    color: 'bg-gray-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T13:15:00'),
    imp: true,
    domain: 'esummit',
    time: '1:15 PM - 2:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/advisoryandlegal.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    speakers: ['sumit-jha', 'chetanbulsari'],
    description:
      'This session focuses on the vital aspects of advisory and legal support for startups and businesses. Learn from experts how to navigate legal frameworks and obtain the right advice to fuel your growth.',
  },
  {
    title: 'Incubation and Grants',
    id: 'incubation-and-grants',
    color: 'bg-indigo-500',
    date: 'Oct 6th, 2024',
    location: 'AISSMS COE',
    start: new Date('2024-10-06T14:15:00'),
    imp: true,
    domain: 'esummit',
    time: '2:15 PM - 3:15 PM',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/incubation.jpeg',
    organizers: [{ name: 'Laukik Patil', phone: '9975875657' }],
    icon: 'IoRocket',
    description:
      'Explore the opportunities of incubation and grants in this insightful session. Learn how to secure funding and resources to accelerate your startup’s growth from early-stage to success.',
  },

  // MUN (Day 2)

  {
    title: 'MUN Breakfast and Reporting',
    icon: 'FcGlobe',
    id: 'breakfast-reporting-day2',
    domain: 'mun',
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Admin Office, 3rd Floor',
    start: new Date('2024-10-06T09:00:00'),
    imp: false,
    time: '9:00 AM - 10:00 AM',
    description: 'Start your day with breakfast and reporting.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/breakfast.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN Lunch',
    icon: 'FcGlobe',
    id: 'lunch-day2',
    domain: 'mun',
    color: 'bg-green-500',
    date: 'Oct 6th, 2024',
    location: '3rd Floor Terrace',
    start: new Date('2024-10-06T13:00:00'),
    imp: false,
    time: '1:00 PM - 2:00 PM',
    description: 'Lunch break for all IOIT MUN 2024 participants.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/munlunch.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'MUN High tea and Closing Ceremony',
    icon: 'FcGlobe',
    id: 'high-tea-closing-ceremony',
    domain: 'mun',
    color: 'bg-orange-500',
    date: 'Oct 6th, 2024',
    location: 'MPH',
    start: new Date('2024-10-06T16:00:00'),
    imp: false,
    time: '4:00 PM - 5:00 PM',
    description: 'High tea and closing ceremony to conclude IOIT MUN 2024.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/events/inaugration.jpeg',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },

  {
    title: 'UNSC Committee Session',
    icon: 'FcGlobe',
    id: 'unsc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unsc',
    registration: MUNLINK,
    color: 'bg-blue-500',
    date: 'Oct 6th, 2024',
    location: 'Room 002',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'The UNSC addresses global peace and security issues, focusing on conflict resolution, sanctions, and peacekeeping efforts to maintain international stability. Agenda: Assessing global export controls and technology transfer under the Wassenaar Arrangement.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unsc.webp',
    organizers: [{ name: 'Gargi Bharshankar' }, { name: 'Aditya Sarade' }],
  },
  {
    title: 'UNHRC Committee Session',
    icon: 'FcGlobe',
    id: 'unhrc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unhrc',
    registration: MUNLINK,
    color: 'bg-red-500',
    date: 'Oct 6th, 2024',
    location: 'Room 305',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'The UNHRC promotes and protects human rights globally through dialogue and cooperation. Agenda: Discussing the role of state and non-state actors in the Venezuelan crisis, with emphasis on the humanitarian emergency following the presidential elections.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unhcr.webp',
    organizers: [{ name: 'Chinmay Nakwa' }, { name: 'Shriya Naphade' }],
  },
  {
    title: 'AIPPM Committee Session',
    icon: 'FcGlobe',
    id: 'aippm-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/aippm',
    registration: MUNLINK,
    color: 'bg-yellow-500',
    date: 'Oct 6th, 2024',
    location: 'Room 206',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'AIPPM brings together diverse political factions to discuss national policies and reforms. Agenda: Deliberating on the introduction of the Aparajita Bill and the demand for a Central Protection Act.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/aippm.jpg',
    organizers: [{ name: 'Tanisha Londhe' }, { name: 'Atharva Pednekar' }],
  },
  {
    title: 'UNCSW Committee Session',
    icon: 'FcGlobe',
    id: 'uncsw-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/uncsw',
    registration: MUNLINK,
    color: 'bg-pink-500',
    date: 'Oct 6th, 2024',
    location: 'Room 405',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'UNCSW is dedicated to promoting gender equality and women’s empowerment globally. Agenda: Implications of human rights violations on women, with emphasis on religion-driven nations.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/uncsw.webp',
    organizers: [{ name: 'Sajal Gulati' }, { name: 'Devang Gandhi' }],
  },
  {
    title: 'UNODC Committee Session',
    icon: 'FcGlobe',
    id: 'unodc-session-day2',
    domain: 'mun',
    munpage: 'https://www.ioitmun.com/unodc',
    registration: MUNLINK,
    color: 'bg-gray-500',
    date: 'Oct 6th, 2024',
    location: 'Room 409',
    start: new Date('2024-10-06T10:00:00'),
    imp: true,
    time: '10:00 AM',
    description:
      'UNODC combats global drug trafficking and organized crime while promoting justice and integrity. Agenda: Addressing the challenges of money and drug laundering in Special Economic Zones, with special emphasis on the Golden Triangle SEZ.',
    image:
      'https://hosteze-little-boy.s3.ap-south-1.amazonaws.com/assets/static/tenet/mun/mun/unodc.jpg',
    organizers: [{ name: 'Aditya Sarade' }, { name: 'Tanisha Londhe' }],
  },
];
