export const gameWords = [
  'technology',
  'negotiations',
  'battlegrounds',
  'product management',
  'consulting',
  'data',
  'business intelligence',
  'cybersecurity',
  'capture the flag',
  'AR',
  'VR',
  'coding',
  'web 3',
  'AI',
  'machine learning',
  'drones',
  'robotics',
  'workshop',
  'gen AI',
  'open mic',
  'stand-up',
  'theater',
  'LAN tournaments',
  'eSports',
  'gaming',
  'experience arenas',
  'MUN',
  'innovation',
  'entrepreneurship',
  'tech startup',
  'software',
  'networking',
  'hackathon',
  'cyber attack',
  'data science',
  'cloud computing',
  'IoT',
  'blockchain',
  'smart city',
  '5G',
  'UX/UI design',
  'app development',
  'AI ethics',
  'biometrics',
  'mixed reality',
  'quantum computing',
  'neural networks',
  'deep learning',
  'data privacy',
  'privacy policies',
  'trends',
  'online gaming',
  'gaming strategy',
  'gamer culture',
  'game design',
  'virtual env',
  'simulation',
  'AI-driven tools',
  'virtual events',
  'digital art',
  'creative coding',
  'tech innovation',
  'startup ecosystem',
  'venture capital',
  'tech conferences',
  'digital security',
  'penetration',
  'risk management',
  'ethical hacking',
  'tech workshops',
  'coding bootcamps',
  'technology ethics',
  'game development',
  'virtual worlds',
  'game mechanics',
  'eSports',
  'user experience',
  'game theory',
  'gamification',
  'cross-platform',
  'cyber security',
  'DevOps',
  'Agile',
  'Scrum',
  'Kanban',
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Jenkins',
  'Docker',
  'Kubernetes',
  'Terraform',
  'Ansible',
  'Puppet',
  'Chef',
  'Maven',
  'Gradle',
  'npm',
  'Yarn',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'Ruby on Rails',
  'Spring Boot',
  'Laravel',
  'ASP.NET',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Jupyter Notebook',
  'Anaconda',
  'R Studio',
  'MATLAB',
  'Hadoop',
  'Spark',
  'Flink',
  'Kafka',
  'Redis',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Oracle',
  'SQL Server',
  'Elasticsearch',
  'Kibana',
  'Logstash',
  'Grafana',
  'Prometheus',
  'Tableau',
  'Power BI',
  'Looker',
  'SAS',
  'SPSS',
  'Salesforce',
  'SAP',
  'Oracle Cloud',
  'Google Cloud Platform',
  'Microsoft Azure',
  'Amazon Web Services',
  'Heroku',
  'DigitalOcean',
  'VMware',
  'VirtualBox',
  'Vagrant',
  'Nginx',
  'Apache',
  'IIS',
  'Unity',
  'Unreal Engine',
  'Blender',
  'AutoCAD',
  'SOLIDWORKS',
  'JIRA',
  'Trello',
  'Asana',
  'Slack',
  'Microsoft Teams',
  'Zoom',
  'WebEx',
  'Skype',
  'Discord',
  'Figma',
  'Sketch',
  'Adobe Creative Suite',
  'InVision',
  'Axure',
  'Balsamiq',
  'Selenium',
  'JUnit',
  'TestNG',
  'Mocha',
  'Jest',
  'Cypress',
  'Postman',
  'SoapUI',
  'Wireshark',
  'Metasploit',
  'Nmap',
  'Burp Suite',
  'Splunk',
  'Nagios',
  'Zabbix',
  'Ansible Tower',
  'Puppet Enterprise',
  'Chef Automate',
  'CircleCI',
  'Travis CI',
  'GitLab CI/CD',
  'ArgoCD',
  'Helm',
  'Istio',
  'Linkerd',
  'Consul',
  'Etcd',
  'ZooKeeper',
  'RabbitMQ',
  'Apache Airflow',
  'Dagster',
  'Luigi',
  'Prefect',
  'Databricks',
  'Snowflake',
  'Redshift',
  'BigQuery',
  'Athena',
  'Presto',
  'Hive',
  'Cassandra',
  'Neo4j',
  'GraphQL',
  'Apollo',
  'FastAPI',
  'gRPC',
  'Swagger',
  'OpenAPI',
  'infrastructure',
  'digital media',
  'game narratives',
  'storytelling',
  'smart devices',
  'tech startups',
  'tech trends',
  'digital innovation',
  'technology policy',
  'ethics in AI',
  'AI in healthcare',
  'entrepreneurship',
  'social good',
  'AI research',
  'education',
  'communities',
  'immersive tech',
  'gaming platforms',
  'hardware',
  'software platforms',
  'AI applications',
  'cyber threats',
  'data engineering',
  'ethics',
  'multiplayer',
  'AI-driven gaming',
  'simulation',
  'eSports',
  'game studios',
  'gaming hardware',
  'technology',
  'AI models',
  'blockchain ',
  'technology',
  'negotiations',
  'battlegrounds',
  'product management',
  'consulting',
  'data',
  'business intelligence',
  'cybersecurity',
  'capture the flag',
  'AR',
  'VR',
  'coding',
  'web 3',
  'AI',
  'machine learning',
  'drones',
  'robotics',
  'workshop',
  'gen AI',
  'open mic',
  'stand-up',
  'theater',
  'LAN tournaments',
  'eSports',
  'gaming',
  'experience arenas',
  'MUN',
  'innovation',
  'entrepreneurship',
  'tech startup',
  'software',
  'networking',
  'hackathon',
  'cyber attack',
  'data science',
  'cloud computing',
  'IoT',
  'blockchain',
  'smart city',
  '5G',
  'UX/UI design',
  'app development',
  'AI ethics',
  'biometrics',
  'mixed reality',
  'quantum computing',
  'neural networks',
  'deep learning',
  'data privacy',
  'privacy policies',
  'trends',
  'online gaming',
  'gaming strategy',
  'gamer culture',
  'game design',
  'virtual env',
  'simulation',
  'AI-driven tools',
  'virtual events',
  'digital art',
  'creative coding',
  'tech innovation',
  'startup ecosystem',
  'venture capital',
  'tech conferences',
  'digital security',
  'penetration',
  'risk management',
  'ethical hacking',
  'tech workshops',
  'coding bootcamps',
  'technology ethics',
  'game development',
  'virtual worlds',
  'game mechanics',
  'eSports',
  'user experience',
  'game theory',
  'gamification',
  'cross-platform',
  'cyber security',
  'infrastructure',
  'digital media',
  'game narratives',
  'storytelling',
  'smart devices',
  'tech startups',
  'tech trends',
  'digital innovation',
  'technology policy',
  'ethics in AI',
  'AI in healthcare',
  'entrepreneurship',
  'social good',
  'AI research',
  'education',
  'communities',
  'immersive tech',
  'gaming platforms',
  'software platforms',
  'AI applications',
  'cyber threats',
  'data engineering',
  'ethics',
  'multiplayer',
  'simulation',
  'eSports',
  'game studios',
  'gaming hardware',
  'technology',
  'AI models',
  'technology',
  'artificial intelligence',
  'machine learning',
  'cloud computing',
  'computer science',
  'data science',
  'big data',
  'neural networks',
  'deep learning',
  'algorithm',
  'data analysis',
  'robotics',
  'automation',
  'software development',
  'cybersecurity',
  'IoT',
  'blockchain',
  'quantum computing',
  'data privacy',
  'AI ethics',
  'computer vision',
  'computational theory',
  'network security',
  'cloud storage',
  'virtualization',
  'IT infrastructure',
  'programming',
  'software engineering',
  'user experience',
  'UI/UX design',
  'tech innovation',
  'digital transformation',
  'social impact',
  'economic development',
  'sustainable technology',
  'tech for good',
  'technology policy',
  'digital equity',
  'economic growth',
  'social entrepreneurship',
  'e-governance',
  'data governance',
  'tech entrepreneurship',
  'economic inclusion',
  'technology adoption',
  'digital literacy',
  'cyber resilience',
  'AI-driven solutions',
  'ethical AI',
  'tech-driven economy',
  'technology access',
  'economic justice',
  'impact investing',
  'digital divide',
  'social innovation',
  'tech for social good',
  'AI research',
  'digital economy',
  'cloud services',
  'technology trends',
  'advanced technologies',
  'smart technologies',
  'data-driven decisions',
  'software solutions',
  'tech startups',
  'innovation ecosystem',
  'economic sustainability',
  'blockchain ',
  'LinkedIn',
  'resume',
  'CV',
  'cover letter',
  'job application',
  'interview',
  'networking',
  'career fair',
  'job board',
  'Indeed',
  'Glassdoor',
  'Monster',
  'ZipRecruiter',
  'CareerBuilder',
  'headhunter',
  'recruiter',
  'human resources',
  'HR',
  'talent acquisition',
  'onboarding',
  'professional development',
  'skill set',
  'portfolio',
  'internship',
  'apprenticeship',
  'mentorship',
  'career path',
  'job description',
  'salary negotiation',
  'benefits package',
  'remote work',
  'freelancing',
  'gig economy',
  'side hustle',
  'career change',
  'upskilling',
  'reskilling',
  'continuing education',
  'certification',
  'professional license',
  'job market',
  'employment trends',
  'workforce',
  'job security',
  'work-life balance',
  'corporate culture',
  'company values',
  'startup culture',
  'employee engagement',
  'performance review',
  'promotion',
  'career advancement',
  'leadership development',
  'management training',
  'executive coaching',
  'personal branding',
  'elevator pitch',
  'professional network',
  'alumni network',
  'industry conference',
  'webinar',
  'workshop',
  'professional association',
  'trade organization',
  'job shadowing',
  'informational interview',
  'reference check',
  'background check',
  'job offer',
  'counteroffers',
  'resignation letter',
  'exit interview',
  'severance package',
  'unemployment benefits',
  'career counseling',
  'outplacement services',
  'job satisfaction',
  'workplace diversity',
  'inclusion',
  'equal opportunity',
  'affirmative action',
  'work permit',
  'visa sponsorship',
  'relocation package',
  'remote team',
  'distributed workforce',
  'coworking space',
  'flexible hours',
  'part-time work',
  'full-time employment',
  'contract work',
  'temp agency',
  'staffing firm',
  'talent pool',
  'skills gap',
  'employee retention',
  'turnover rate',
  'career plateau',
  'burnout',
  'work ethic',
  'soft skills',
  'hard skills',
  'transferable skills',
  'industry expertise',
  'thought leadership',
  'personal growth',
  'career goals',
  'job hunting',
  'job seeker',
];
